version: 2.1

jobs:
  vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:0.49.1
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y libssl-dev
      - run: make examples

workflows:
  version: 2.1

  commit:
    jobs:
      - vs-ponyc-release
